create database customer_behavior;
use customer_behavior;
Select * from customer_behavior.customer;

-- Q1 what is the total revenue generated by male and female customer 
select gender, sum(purchase_amount) as revenue
from customer_behavior.customer
group by gender;

-- Q2 which customer used discount but still pay more than average purchase amount
Select customer_id , purchase_amount
from customer_behavior.customer where discount_applied = "yes" 
and purchase_amount >= (Select avg(purchase_amount) from customer_behavior.customer);

-- Q3 which are the Top 5 products with highest avg review rating
select item_purchased , round(avg(review_rating),2) as avg_prod_rating from customer_behavior.customer
group by item_purchased
order by avg_prod_rating desc
limit 5;

-- Q4 compare the avg purchase amount between standar and express shipping
select shipping_type , round(avg(purchase_amount),2) as Avg_purchase_amt from customer_behavior.customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5 Do subscribed customers spend more?compare average spend and total revenue between subscribers and non-subscribers
Select subscription_status , count(customer_id) as Total_Customers , avg(purchase_amount) as Avg_spend , sum(purchase_amount) as Total_spend
from customer_behavior.customer
group by subscription_status
order  by Total_spend , Avg_spend desc;

-- Q6 which 5 products have the higheast percentage of purchase with discount applied
select item_purchased , round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*)*100,2) as discount_rate
from customer_behavior.customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 Segment customers into New , Returning, and loyal based on their number of previous purchases , and show the count of each segment
with customer_type as(
select customer_id , previous_purchases , 
case 
	when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as segment
 from customer_behavior.customer
)
select segment , count(*) as No_of_customers from customer_type
group by segment;

-- Q8 What are the top 3 most purchase product with each category

with item_count as(
select category , item_purchased , count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_behavior.customer
group by category, item_purchased
)
select item_rank, category , item_purchased , total_orders from item_count where item_rank <=3;

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers from customer_behavior.customer
where previous_purchases > 5
group by subscription_status;

-- Q10 what is the revenue contribution of each age group
Select  age_group , sum(purchase_amount) as total_revenue
from customer_behavior.customer
group by age_group
order by total_revenue desc;

